[firebase_client]
"apiKey"="AIzaSyAiSXq0LBNDdKBmqrDs9tpyngFMi-p8blE"
"authDomain"="streamlit-chat-24c01.firebaseapp.com"
"databaseURL"="https://streamlit-chat-24c01-default-rtdb.asia-southeast1.firebasedatabase.app"
"projectId"="streamlit-chat-24c01"
"storageBucket"="streamlit-chat-24c01.firebasestorage.app"
"messagingSenderI"="528070221329"
"appId"="1:528070221329:web:55b9d750b2c78be72f9bb0"
"measurementId"="G-N891CB4SFR"

[firebase_admin]
"type"="service_account"
"project_id"="streamlit-chat-24c01"
"private_key_id"="838077f977562eece915e4f2d613a441095e4a18"
"private_key"="-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCn/kZr/jgzGt+d\n2CcoqLKaGtun+t6YZ6JJZ28bPprSpqVLfsg5zPg5aJQAgzg9ptTJj683ZifNWgTt\nUOACeAzAEuVs/I/m/VmKRm55UNdAPo921nTbAaPVjN7BjmkZKzJj7LNVD7ic6428\nAe5AbK9PrRZKaseiYHk3t/mQQmWwuiCFLrcgGjnXdMGLhpkOgLK0dQQTLGZ79pev\nS4z9l+SYe74HjYOVEskj916PK5urKbFNDvvMmOd/MJpYAgjwyzQBZfwHUCx0cpYV\nbWIVr+L4fVxgClWUe4UuJLluNEgusos4y3OW2390CO7C2lXgIIFioge64l4fF+r/\nahEyRjfdAgMBAAECggEADIHUneEvL3Tafa60WaVXqLwDqwm1LV0X2sWx4rIiRjkk\neM6vWwhM2b9Ut4YNd5+WW4xQQ/xdzb7cO4voJZ7o+hreDGNwVkb59d7BBlSzteOC\nfFtCl3STjUhf5EK1ReuupHxgrJ5PRRWPd5YgNhkxYyn0jSVOiCMNG04d7TTYS9Qs\nypFnAdZK7a8RV1V+jcM2spICE4Kv5y9p1YfW5QA9kEK9/XxiZbroxRMgCmmQxVnn\np4DVGNpmaf5+LXNjPpIUIADWbMJ9n5ca1x80ay24cqSkvlHm+sJxPwogVZU2cY8R\n8u0BP+0Eb759iYqiCEFV27P8ncCneJoueKCd/XnggQKBgQDRmf1ubuxvSZVddXEJ\nkoUzvJRqWtZzFYQKt1wQTkXvA+diTTunpmaO8XkcXyeTHZV4Bh/Vgb2Lol5YaFHB\nLzd8zw1r5RaJ4rhFCnIvVLe/JzEd5v3TnVu3xY1IwYdDUElS6POuncQPYCAP+ac5\nIThonZvRAGwRL77zgPfbYwGUXQKBgQDNLl3PutSH4gRTk9Es8AnmeI4grXK4a7eH\n3nd8U3F2X7dNJKNElcOqwMoX+c/K9ggfi/tG/vNFEjl9m4ByQbX+GgQsajbi+0Db\n4pejzNvhN7+FKTnFY+EkrOWzjx8OCUn9EEtlzSZEWIpZYv97FmBOViSq01E74f/w\nfIohBxz5gQKBgDzcsCBfCTyPa1XGAlq7Nv585cO0OM0WFE9gStVZRSlQQuHid04J\nHYKoT3iTkNRBJOPDM381uypOrYKSWBr2cPBG1yjbTp4fPU6e5+UifnB9GuAJ8O5/\npOBJ9uqHd5VuPLxcdFXh7cphKS46WfpW0SBfk50uuDKNYK8oZdBIgW7pAoGAM7OV\nS/zmBP9825qJwOsTc5G5Lp7GI5Zw/rmeHiPgmVVxGO08ftHGJkbCJdx68cehMGHT\nhYZEwojfF7mRWjkYpNjlaFOzVOq+4ylr0IiUd2HWzrUeq5CJcPZoQyCzUJQiorPy\na8qP8/Tjl7aMbfWretHWF318ILzIA08+dygVswECgYBJgWudfoJYadjflH27jgVH\ni8gpjRwKlHiht8Bd7/40Sojftf90aDnaX2RAcRThemwqAVVo+thMnBhzKdbO6k40\nK0e6gZmTMzOJAdLl1xOt8HLdGxkNCSa7J2zvKqBCw+2noAPruQ4q9r3CPYJ2QkYj\nPu7rNbDESS7Woc5QhkeEjQ==\n-----END PRIVATE KEY-----\n"
"client_email"="firebase-adminsdk-fbsvc@streamlit-chat-24c01.iam.gserviceaccount.com"
"client_id"="104454973789855376040"
"auth_uri"="https://accounts.google.com/o/oauth2/auth"
"token_uri"="https://oauth2.googleapis.com/token"
"auth_provider_x509_cert_url"="https://www.googleapis.com/oauth2/v1/certs"
"client_x509_cert_url"="https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40streamlit-chat-24c01.iam.gserviceaccount.com"
"universe_domain"="googleapis.com"


